# Generated by Django 5.2.4 on 2025-07-23 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('menopausal_status', models.CharField(blank=True, max_length=10, null=True)),
                ('family_history', models.CharField(blank=True, max_length=3, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('menarche_age', models.PositiveIntegerField(blank=True, null=True)),
                ('breastfeeding_history', models.CharField(blank=True, max_length=3, null=True)),
                ('alcohol_consumption', models.CharField(blank=True, max_length=3, null=True)),
                ('hormonal_treatment_history', models.CharField(blank=True, max_length=3, null=True)),
                ('physical_activity', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10, null=True)),
                ('breast_pain', models.CharField(blank=True, max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
