# Generated by Django 5.2.4 on 2025-07-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0003_medicalimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
