# Generated by Django 5.2.4 on 2025-07-30 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0005_riskresult_diagnosisrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20)),
                ('prediction_percentage', models.FloatField()),
                ('mode', models.CharField(choices=[('symptoms', 'Symptoms'), ('image', 'Image')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='diagnosisrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='RiskResult',
        ),
        migrations.DeleteModel(
            name='DiagnosisRecord',
        ),
    ]
