# Generated by Django 5.2.4 on 2025-08-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0007_riskassessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskassessment',
            old_name='level_percent',
            new_name='percentage',
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='mode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_level',
            field=models.CharField(max_length=20),
        ),
    ]
