# Generated by Django 5.2.4 on 2025-08-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0009_rename_percentage_riskassessment_prediction_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='breast_cancer',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
