# Generated by Django 5.2.4 on 2025-08-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0010_symptoms_breast_cancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='risk_images/'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_level',
            field=models.CharField(max_length=20),
        ),
    ]
