# Generated by Django 5.2.4 on 2025-08-08 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0013_rename_notes_profile_note_profile_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='history_images/'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='mode',
            field=models.CharField(choices=[('symptoms', 'Symptoms'), ('image', 'Image')], max_length=20),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='prediction_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
